# Site settings
author: Sim Greenbaum
title: My  Coding  Journey
header-img: img/home-bg.png
email: gbs4ever2@gmail.com
copyright_name: Sim Greenbaum
description: > # this means to ignore newlines until "baseurl:"
  Journey through Flatiron
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  gbs4ever

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
